Feature/dev 84
sharefinancialledger/share-financialledger-server pull request #15
Opened 2022-01-29 11:48 UTC by lowelllll

2022-02-05 18:44 UTC, Root-kjh commented on src/main/kotlin/com/sharefinancialledger/domain/category/controller/dto/Response.kt
> +        fun of(category: Category) = CategoryResponse(
kotlin 혹은 spring에서 of라는 펑션네임이 자주 쓰이는 편인가요? 장고 쓸때는 보지 못했던 네이밍이라서요

2022-02-05 18:44 UTC, Root-kjh commented
👍

2022-02-05 18:44 UTC, Root-kjh submitted a review, later dismissed

2022-02-07 15:18 UTC, lowelllll commented on src/main/kotlin/com/sharefinancialledger/domain/category/controller/dto/Response.kt
> +        fun of(category: Category) = CategoryResponse(
[java static factory method naming convention](https://velog.io/@bosl95/%EC%9E%90%EB%B0%94%EC%9D%98-Static-Factory-Method)입니다 

kotlin에서는 listOf, LocalDateTime.of() 등으로 자주 쓰입니다.
레퍼런스찾아보면서 매개변수가 하나라 of보다는 from이 더 적합해보여서 from으로 변경했습니다

2022-02-09 12:29 UTC, Root-kjh approved these changes

2022-02-09 12:30 UTC, Root-kjh commented on src/main/kotlin/com/sharefinancialledger/domain/category/controller/dto/Response.kt
> +        fun of(category: Category) = CategoryResponse(
확인했습니다!

2022-02-09 12:31 UTC, Root-kjh requested changes
test

2022-02-09 12:32 UTC, Root-kjh requested changes
test

2022-02-09 12:32 UTC, Root-kjh approved these changes
test

2022-02-09 12:57 UTC, merged